name: Terraform plan Difference
on:
  pull_request:
    branches:
      - master

jobs:
# Update 'Job name' and 'terraform_directory' as needed based on the module structure.
  linux-container-example:
    if: github.actor != 'dependabot[bot]'
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-pr-checks.yaml@master
    with:
      provider: 'azurerm'
      terraform_directory: 'examples/linux_container'
      target_branch: 'master'
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}

  linux-web-app-example:
    if: github.actor != 'dependabot[bot]'
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-pr-checks.yaml@master
    with:
      provider: 'azurerm'
      terraform_directory: 'examples/linux_web_app'
      target_branch: 'master'
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}

  windows-web-app-example:
    if: github.actor != 'dependabot[bot]'
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-pr-checks.yaml@master
    with:
      provider: 'azurerm'
      terraform_directory: 'examples/windows_web_app'
      target_branch: 'master'
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}